name: Tests
on: 
  push:
    branches: ["master"]
  
  pull_request:
    branches: ["master"]

jobs:
  skipci:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "${{ contains(github.event.head_commit.message, '[percy]') }} - ${{ toJSON(github.event) }}"
  build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[percy]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: v1/${{ runner.os }}/pip/${{ hashFiles('**/{requirements,development}.txt') }}
          restore-keys: v1/${{ runner.os }}/pip/
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1/${{ runner.os }}/node-12/${{ hashFiles('**/package-lock.lock') }}
          restore-keys: v1/${{ runner.os }}/node-16/
      - name: Run tests
        run: make test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
