name: Tests
on: 
  push:
    branches: ["master"]
  
  pull_request:
    branches: ["master"]

jobs:

  skipci:
    runs-on: ubuntu-18.04
    steps:
      # Checkout that works with "push" and "pull_request" trigger event
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

        # Set environment variables based on the last commit
      - name: Check if message contain keywords as scope to do visual test
        id: check_commit
        run: |
          message=$(git log -1 --pretty=format:'%s')
          if [[ $message =~ "\[(percy|vrt|visual[-_\s*]test|visual)\]" ]]; then
            echo "::set-output name=match::true"
            echo "$message -> Match is true"
          else
            echo "$message -> Match is false"
          fi
    outputs:
      match: ${{ steps.check_commit.outputs.match }}

  build:
    runs-on: ubuntu-latest
    needs: skipci
    
    if: steps.check_commit.outputs.match == 'true'
    steps:
    
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: v1/${{ runner.os }}/pip/${{ hashFiles('**/{requirements,development}.txt') }}
          restore-keys: v1/${{ runner.os }}/pip/
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1/${{ runner.os }}/node-12/${{ hashFiles('**/package-lock.lock') }}
          restore-keys: v1/${{ runner.os }}/node-16/
      - name: Run tests
        run: make test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
